tittle: Amarachi Okorie Data Analytics Potforlio
Logo: Kerris.jpg
Description: With over three years of experience in data analysis, I excel in working with diverse data sources and transforming complex datasets into actionable insights that support informed decision-making. My strong problem-solving skills, keen attention to detail, and polished presentation abilities have been refined through my work as a data analyst with various clients.I am proficient in statistical analysis, data mining, and visualization techniques, which allow me to uncover valuable insights and identify trends.
#Show_downloads: True
#Google_analytics:
Theme: jekyll.theme.minimal
